catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade

catalogs:
  cli:
    '@antfu/eslint-config': ^6.6.1
    '@antfu/ni': ^28.0.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.16
    simple-git-hooks: ^2.13.1
    tsdown: ^0.17.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.2.7
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.15
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.1
  conflicts_age-encryption_h0_3_0:
    age-encryption: ^0.3.0
  conflicts_chalk_h5_0_0:
    chalk: ^5.0.0
  conflicts_commander_h12_0_0:
    commander: ^12.0.0
  conflicts_fs-extra_h11_0_0:
    fs-extra: ^11.0.0
  conflicts_inquirer_h9_0_0:
    inquirer: ^9.0.0
  conflicts_simple-git_h3_0_0:
    simple-git: ^3.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
catalog:
  '@types/fs-extra': ^11.0.0
  '@types/inquirer': ^9.0.9
  age-encryption: ^0.0.0
  chalk: ^0.0.0
  commander: ^0.0.0
  fs-extra: ^0.0.0
  inquirer: ^0.0.0
  simple-git: ^0.0.0
